require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

# context ごとに let! を使い分けたい場合があるため無効に
RSpec/LetSetup:
  Enabled: false
